#!/bin/bash

docker run \
  --rm \
  --tty \
  --interactive \
  --user 1000 \
  --volume ./site:/site \
  --net currency-conversion \
  --publish 5173:5173 \
  --add-host=host.docker.internal:host-gateway \
  --name cc-node \
  node bash
